// Mocks generated by Mockito 5.4.4 from annotations
// in mystiq_fortune_app/test/database/mongodb_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mongo_dart/mongo_dart.dart' as _i2;
import 'package:mongo_dart/src/database/commands/administration_commands/drop_command/drop_options.dart'
    as _i9;
import 'package:mongo_dart/src/database/commands/administration_commands/drop_database_command/drop_database_options.dart'
    as _i6;
import 'package:mongo_dart/src/database/commands/administration_commands/list_collections_command/list_collections_options.dart'
    as _i8;
import 'package:mongo_dart/src/database/commands/operation.dart' as _i3;
import 'package:mongo_dart/src/database/message/mongo_modern_message.dart'
    as _i5;
import 'package:mongo_dart_query/mongo_dart_query.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeState_0 extends _i1.SmartFake implements _i2.State {
  _FakeState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeReadPreference_1 extends _i1.SmartFake
    implements _i3.ReadPreference {
  _FakeReadPreference_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConnection_2 extends _i1.SmartFake implements _i2.Connection {
  _FakeConnection_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDbCollection_3 extends _i1.SmartFake implements _i2.DbCollection {
  _FakeDbCollection_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMongoReplyMessage_4 extends _i1.SmartFake
    implements _i2.MongoReplyMessage {
  _FakeMongoReplyMessage_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Db].
///
/// See the documentation for Mockito's code generation for more information.
class MockDb extends _i1.Mock implements _i2.Db {
  MockDb() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.State get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeState_0(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.State);

  @override
  set state(_i2.State? _state) => super.noSuchMethod(
        Invocation.setter(
          #state,
          _state,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set databaseName(String? _databaseName) => super.noSuchMethod(
        Invocation.setter(
          #databaseName,
          _databaseName,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set authSourceDb(_i2.Db? _authSourceDb) => super.noSuchMethod(
        Invocation.setter(
          #authSourceDb,
          _authSourceDb,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.ReadPreference get readPreference => (super.noSuchMethod(
        Invocation.getter(#readPreference),
        returnValue: _FakeReadPreference_1(
          this,
          Invocation.getter(#readPreference),
        ),
      ) as _i3.ReadPreference);

  @override
  set readPreference(_i3.ReadPreference? _readPreference) => super.noSuchMethod(
        Invocation.setter(
          #readPreference,
          _readPreference,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.Connection get masterConnection => (super.noSuchMethod(
        Invocation.getter(#masterConnection),
        returnValue: _FakeConnection_2(
          this,
          Invocation.getter(#masterConnection),
        ),
      ) as _i2.Connection);

  @override
  _i2.Connection get masterConnectionAnyState => (super.noSuchMethod(
        Invocation.getter(#masterConnectionAnyState),
        returnValue: _FakeConnection_2(
          this,
          Invocation.getter(#masterConnectionAnyState),
        ),
      ) as _i2.Connection);

  @override
  List<String> get uriList => (super.noSuchMethod(
        Invocation.getter(#uriList),
        returnValue: <String>[],
      ) as List<String>);

  @override
  bool get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: false,
      ) as bool);

  @override
  void selectAuthenticationMechanism(String? authenticationSchemeName) =>
      super.noSuchMethod(
        Invocation.method(
          #selectAuthenticationMechanism,
          [authenticationSchemeName],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.DbCollection collection(String? collectionName) => (super.noSuchMethod(
        Invocation.method(
          #collection,
          [collectionName],
        ),
        returnValue: _FakeDbCollection_3(
          this,
          Invocation.method(
            #collection,
            [collectionName],
          ),
        ),
      ) as _i2.DbCollection);

  @override
  _i4.Future<_i2.MongoReplyMessage> queryMessage(
    _i2.MongoMessage? queryMessage, {
    _i2.Connection? connection,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #queryMessage,
          [queryMessage],
          {#connection: connection},
        ),
        returnValue:
            _i4.Future<_i2.MongoReplyMessage>.value(_FakeMongoReplyMessage_4(
          this,
          Invocation.method(
            #queryMessage,
            [queryMessage],
            {#connection: connection},
          ),
        )),
      ) as _i4.Future<_i2.MongoReplyMessage>);

  @override
  void executeMessage(
    _i2.MongoMessage? message,
    _i2.WriteConcern? writeConcern, {
    _i2.Connection? connection,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #executeMessage,
          [
            message,
            writeConcern,
          ],
          {#connection: connection},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<Map<String, Object?>> executeModernMessage(
    _i5.MongoModernMessage? message, {
    _i2.Connection? connection,
    bool? skipStateCheck = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #executeModernMessage,
          [message],
          {
            #connection: connection,
            #skipStateCheck: skipStateCheck,
          },
        ),
        returnValue:
            _i4.Future<Map<String, Object?>>.value(<String, Object?>{}),
      ) as _i4.Future<Map<String, Object?>>);

  @override
  _i4.Future<dynamic> open({
    _i2.WriteConcern? writeConcern = _i2.WriteConcern.acknowledged,
    bool? secure = false,
    bool? tlsAllowInvalidCertificates = false,
    String? tlsCAFile,
    String? tlsCertificateKeyFile,
    String? tlsCertificateKeyFilePassword,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #open,
          [],
          {
            #writeConcern: writeConcern,
            #secure: secure,
            #tlsAllowInvalidCertificates: tlsAllowInvalidCertificates,
            #tlsCAFile: tlsCAFile,
            #tlsCertificateKeyFile: tlsCertificateKeyFile,
            #tlsCertificateKeyFilePassword: tlsCertificateKeyFilePassword,
          },
        ),
        returnValue: _i4.Future<dynamic>.value(),
      ) as _i4.Future<dynamic>);

  @override
  _i4.Future<Map<String, dynamic>> executeDbCommand(
    _i2.MongoMessage? message, {
    _i2.Connection? connection,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #executeDbCommand,
          [message],
          {#connection: connection},
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  bool documentIsNotAnError(dynamic firstRepliedDocument) =>
      (super.noSuchMethod(
        Invocation.method(
          #documentIsNotAnError,
          [firstRepliedDocument],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<bool> dropCollection(String? collectionName) =>
      (super.noSuchMethod(
        Invocation.method(
          #dropCollection,
          [collectionName],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<dynamic> drop() => (super.noSuchMethod(
        Invocation.method(
          #drop,
          [],
        ),
        returnValue: _i4.Future<dynamic>.value(),
      ) as _i4.Future<dynamic>);

  @override
  _i4.Future<Map<String, dynamic>> removeFromCollection(
    String? collectionName, [
    Map<String, dynamic>? selector = const {},
    _i2.WriteConcern? writeConcern,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFromCollection,
          [
            collectionName,
            selector,
            writeConcern,
          ],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getLastError(
          [_i2.WriteConcern? writeConcern]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLastError,
          [writeConcern],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getNonce({_i2.Connection? connection}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNonce,
          [],
          {#connection: connection},
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getBuildInfo({_i2.Connection? connection}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBuildInfo,
          [],
          {#connection: connection},
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> isMaster({_i2.Connection? connection}) =>
      (super.noSuchMethod(
        Invocation.method(
          #isMaster,
          [],
          {#connection: connection},
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> wait() => (super.noSuchMethod(
        Invocation.method(
          #wait,
          [],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<dynamic> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i4.Future<dynamic>.value(),
      ) as _i4.Future<dynamic>);

  @override
  _i4.Future<List<dynamic>> listDatabases() => (super.noSuchMethod(
        Invocation.method(
          #listDatabases,
          [],
        ),
        returnValue: _i4.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i4.Future<List<dynamic>>);

  @override
  _i4.Stream<Map<String, dynamic>> collectionsInfoCursor(
          [String? collectionName]) =>
      (super.noSuchMethod(
        Invocation.method(
          #collectionsInfoCursor,
          [collectionName],
        ),
        returnValue: _i4.Stream<Map<String, dynamic>>.empty(),
      ) as _i4.Stream<Map<String, dynamic>>);

  @override
  _i4.Future<List<String?>> listCollections() => (super.noSuchMethod(
        Invocation.method(
          #listCollections,
          [],
        ),
        returnValue: _i4.Future<List<String?>>.value(<String?>[]),
      ) as _i4.Future<List<String?>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getCollectionInfos(
          [Map<String, dynamic>? filter = const {}]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCollectionInfos,
          [filter],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<String?>> getCollectionNames(
          [Map<String, dynamic>? filter = const {}]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCollectionNames,
          [filter],
        ),
        returnValue: _i4.Future<List<String?>>.value(<String?>[]),
      ) as _i4.Future<List<String?>>);

  @override
  _i4.Future<bool> authenticate(
    String? userName,
    String? password, {
    _i2.Connection? connection,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #authenticate,
          [
            userName,
            password,
          ],
          {#connection: connection},
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<List<dynamic>> indexInformation([String? collectionName]) =>
      (super.noSuchMethod(
        Invocation.method(
          #indexInformation,
          [collectionName],
        ),
        returnValue: _i4.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i4.Future<List<dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> createIndex(
    String? collectionName, {
    String? key,
    Map<String, dynamic>? keys,
    bool? unique,
    bool? sparse,
    bool? background,
    bool? dropDups,
    Map<String, dynamic>? partialFilterExpression,
    String? name,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createIndex,
          [collectionName],
          {
            #key: key,
            #keys: keys,
            #unique: unique,
            #sparse: sparse,
            #background: background,
            #dropDups: dropDups,
            #partialFilterExpression: partialFilterExpression,
            #name: name,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<dynamic> ensureIndex(
    String? collectionName, {
    String? key,
    Map<String, dynamic>? keys,
    bool? unique,
    bool? sparse,
    bool? background,
    bool? dropDups,
    Map<String, dynamic>? partialFilterExpression,
    String? name,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #ensureIndex,
          [collectionName],
          {
            #key: key,
            #keys: keys,
            #unique: unique,
            #sparse: sparse,
            #background: background,
            #dropDups: dropDups,
            #partialFilterExpression: partialFilterExpression,
            #name: name,
          },
        ),
        returnValue: _i4.Future<dynamic>.value(),
      ) as _i4.Future<dynamic>);

  @override
  _i4.Future<Map<String, Object?>> modernDropDatabase({
    _i6.DropDatabaseOptions? dropOptions,
    Map<String, Object>? rawOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #modernDropDatabase,
          [],
          {
            #dropOptions: dropOptions,
            #rawOptions: rawOptions,
          },
        ),
        returnValue:
            _i4.Future<Map<String, Object?>>.value(<String, Object?>{}),
      ) as _i4.Future<Map<String, Object?>>);

  @override
  _i4.Future<Map<String, Object?>> serverStatus(
          {Map<String, Object>? options}) =>
      (super.noSuchMethod(
        Invocation.method(
          #serverStatus,
          [],
          {#options: options},
        ),
        returnValue:
            _i4.Future<Map<String, Object?>>.value(<String, Object?>{}),
      ) as _i4.Future<Map<String, Object?>>);

  @override
  _i4.Future<Map<String, Object?>> createCollection(
    String? name, {
    _i3.CreateCollectionOptions? createCollectionOptions,
    Map<String, Object>? rawOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCollection,
          [name],
          {
            #createCollectionOptions: createCollectionOptions,
            #rawOptions: rawOptions,
          },
        ),
        returnValue:
            _i4.Future<Map<String, Object?>>.value(<String, Object?>{}),
      ) as _i4.Future<Map<String, Object?>>);

  @override
  _i4.Stream<Map<String, dynamic>> modernListCollections({
    _i7.SelectorBuilder? selector,
    Map<String, Object?>? filter,
    _i8.ListCollectionsOptions? findOptions,
    Map<String, Object>? rawOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #modernListCollections,
          [],
          {
            #selector: selector,
            #filter: filter,
            #findOptions: findOptions,
            #rawOptions: rawOptions,
          },
        ),
        returnValue: _i4.Stream<Map<String, dynamic>>.empty(),
      ) as _i4.Stream<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, Object?>> createView(
    String? view,
    String? source,
    List<dynamic>? pipeline, {
    _i3.CreateViewOptions? createViewOptions,
    Map<String, Object>? rawOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createView,
          [
            view,
            source,
            pipeline,
          ],
          {
            #createViewOptions: createViewOptions,
            #rawOptions: rawOptions,
          },
        ),
        returnValue:
            _i4.Future<Map<String, Object?>>.value(<String, Object?>{}),
      ) as _i4.Future<Map<String, Object?>>);

  @override
  _i4.Future<Map<String, Object?>> modernDrop(
    String? collectionNAme, {
    _i9.DropOptions? dropOptions,
    Map<String, Object>? rawOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #modernDrop,
          [collectionNAme],
          {
            #dropOptions: dropOptions,
            #rawOptions: rawOptions,
          },
        ),
        returnValue:
            _i4.Future<Map<String, Object?>>.value(<String, Object?>{}),
      ) as _i4.Future<Map<String, Object?>>);

  @override
  _i4.Stream<Map<String, dynamic>> aggregate(
    List<Map<String, Object>>? pipeline, {
    bool? explain,
    Map<String, Object>? cursor,
    String? hint,
    Map<String, Object>? hintDocument,
    _i3.AggregateOptions? aggregateOptions,
    Map<String, Object>? rawOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #aggregate,
          [pipeline],
          {
            #explain: explain,
            #cursor: cursor,
            #hint: hint,
            #hintDocument: hintDocument,
            #aggregateOptions: aggregateOptions,
            #rawOptions: rawOptions,
          },
        ),
        returnValue: _i4.Stream<Map<String, dynamic>>.empty(),
      ) as _i4.Stream<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, Object?>> runCommand(Map<String, Object>? command) =>
      (super.noSuchMethod(
        Invocation.method(
          #runCommand,
          [command],
        ),
        returnValue:
            _i4.Future<Map<String, Object?>>.value(<String, Object?>{}),
      ) as _i4.Future<Map<String, Object?>>);

  @override
  _i4.Future<Map<String, Object?>> pingCommand() => (super.noSuchMethod(
        Invocation.method(
          #pingCommand,
          [],
        ),
        returnValue:
            _i4.Future<Map<String, Object?>>.value(<String, Object?>{}),
      ) as _i4.Future<Map<String, Object?>>);
}
