// Mocks generated by Mockito 5.4.4 from annotations
// in mystiq_fortune_app/test/unit/services/chat_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:dart_amqp/src/client.dart' as _i7;
import 'package:dart_amqp/src/enums.dart' as _i18;
import 'package:dart_amqp/src/protocol.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i15;
import 'package:mongo_dart/mongo_dart.dart' as _i2;
import 'package:mongo_dart/src/database/commands/administration_commands/drop_command/drop_options.dart'
    as _i14;
import 'package:mongo_dart/src/database/commands/administration_commands/drop_database_command/drop_database_options.dart'
    as _i11;
import 'package:mongo_dart/src/database/commands/administration_commands/list_collections_command/list_collections_options.dart'
    as _i13;
import 'package:mongo_dart/src/database/commands/aggregation_commands/count/count_options.dart'
    as _i17;
import 'package:mongo_dart/src/database/commands/aggregation_commands/count/count_result.dart'
    as _i6;
import 'package:mongo_dart/src/database/commands/aggregation_commands/distinct/distinct_options.dart'
    as _i16;
import 'package:mongo_dart/src/database/commands/aggregation_commands/distinct/distinct_result.dart'
    as _i4;
import 'package:mongo_dart/src/database/commands/operation.dart' as _i3;
import 'package:mongo_dart/src/database/commands/query_and_write_operation_commands/return_classes/abstract_write_result.dart'
    as _i20;
import 'package:mongo_dart/src/database/commands/query_and_write_operation_commands/return_classes/write_concern_error.dart'
    as _i21;
import 'package:mongo_dart/src/database/commands/query_and_write_operation_commands/return_classes/write_error.dart'
    as _i19;
import 'package:mongo_dart/src/database/cursor/modern_cursor.dart' as _i5;
import 'package:mongo_dart/src/database/message/mongo_modern_message.dart'
    as _i10;
import 'package:mongo_dart_query/mongo_dart_query.dart' as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeState_0 extends _i1.SmartFake implements _i2.State {
  _FakeState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeReadPreference_1 extends _i1.SmartFake
    implements _i3.ReadPreference {
  _FakeReadPreference_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConnection_2 extends _i1.SmartFake implements _i2.Connection {
  _FakeConnection_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDbCollection_3 extends _i1.SmartFake implements _i2.DbCollection {
  _FakeDbCollection_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMongoReplyMessage_4 extends _i1.SmartFake
    implements _i2.MongoReplyMessage {
  _FakeMongoReplyMessage_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDb_5 extends _i1.SmartFake implements _i2.Db {
  _FakeDb_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCursor_6 extends _i1.SmartFake implements _i2.Cursor {
  _FakeCursor_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWriteResult_7 extends _i1.SmartFake implements _i3.WriteResult {
  _FakeWriteResult_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBulkWriteResult_8 extends _i1.SmartFake
    implements _i3.BulkWriteResult {
  _FakeBulkWriteResult_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFindAndModifyResult_9 extends _i1.SmartFake
    implements _i3.FindAndModifyResult {
  _FakeFindAndModifyResult_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDistinctResult_10 extends _i1.SmartFake
    implements _i4.DistinctResult {
  _FakeDistinctResult_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeModernCursor_11 extends _i1.SmartFake implements _i5.ModernCursor {
  _FakeModernCursor_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCountResult_12 extends _i1.SmartFake implements _i6.CountResult {
  _FakeCountResult_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConnectionSettings_13 extends _i1.SmartFake
    implements _i7.ConnectionSettings {
  _FakeConnectionSettings_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTuningSettings_14 extends _i1.SmartFake
    implements _i8.TuningSettings {
  _FakeTuningSettings_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeChannel_15 extends _i1.SmartFake implements _i7.Channel {
  _FakeChannel_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamSubscription_16<T> extends _i1.SmartFake
    implements _i9.StreamSubscription<T> {
  _FakeStreamSubscription_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeQueue_17 extends _i1.SmartFake implements _i7.Queue {
  _FakeQueue_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeExchange_18 extends _i1.SmartFake implements _i7.Exchange {
  _FakeExchange_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConsumer_19 extends _i1.SmartFake implements _i7.Consumer {
  _FakeConsumer_19(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Db].
///
/// See the documentation for Mockito's code generation for more information.
class MockDb extends _i1.Mock implements _i2.Db {
  MockDb() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.State get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeState_0(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.State);

  @override
  set state(_i2.State? _state) => super.noSuchMethod(
        Invocation.setter(
          #state,
          _state,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set databaseName(String? _databaseName) => super.noSuchMethod(
        Invocation.setter(
          #databaseName,
          _databaseName,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set authSourceDb(_i2.Db? _authSourceDb) => super.noSuchMethod(
        Invocation.setter(
          #authSourceDb,
          _authSourceDb,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.ReadPreference get readPreference => (super.noSuchMethod(
        Invocation.getter(#readPreference),
        returnValue: _FakeReadPreference_1(
          this,
          Invocation.getter(#readPreference),
        ),
      ) as _i3.ReadPreference);

  @override
  set readPreference(_i3.ReadPreference? _readPreference) => super.noSuchMethod(
        Invocation.setter(
          #readPreference,
          _readPreference,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.Connection get masterConnection => (super.noSuchMethod(
        Invocation.getter(#masterConnection),
        returnValue: _FakeConnection_2(
          this,
          Invocation.getter(#masterConnection),
        ),
      ) as _i2.Connection);

  @override
  _i2.Connection get masterConnectionAnyState => (super.noSuchMethod(
        Invocation.getter(#masterConnectionAnyState),
        returnValue: _FakeConnection_2(
          this,
          Invocation.getter(#masterConnectionAnyState),
        ),
      ) as _i2.Connection);

  @override
  List<String> get uriList => (super.noSuchMethod(
        Invocation.getter(#uriList),
        returnValue: <String>[],
      ) as List<String>);

  @override
  bool get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: false,
      ) as bool);

  @override
  void selectAuthenticationMechanism(String? authenticationSchemeName) =>
      super.noSuchMethod(
        Invocation.method(
          #selectAuthenticationMechanism,
          [authenticationSchemeName],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.DbCollection collection(String? collectionName) => (super.noSuchMethod(
        Invocation.method(
          #collection,
          [collectionName],
        ),
        returnValue: _FakeDbCollection_3(
          this,
          Invocation.method(
            #collection,
            [collectionName],
          ),
        ),
      ) as _i2.DbCollection);

  @override
  _i9.Future<_i2.MongoReplyMessage> queryMessage(
    _i2.MongoMessage? queryMessage, {
    _i2.Connection? connection,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #queryMessage,
          [queryMessage],
          {#connection: connection},
        ),
        returnValue:
            _i9.Future<_i2.MongoReplyMessage>.value(_FakeMongoReplyMessage_4(
          this,
          Invocation.method(
            #queryMessage,
            [queryMessage],
            {#connection: connection},
          ),
        )),
      ) as _i9.Future<_i2.MongoReplyMessage>);

  @override
  void executeMessage(
    _i2.MongoMessage? message,
    _i2.WriteConcern? writeConcern, {
    _i2.Connection? connection,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #executeMessage,
          [
            message,
            writeConcern,
          ],
          {#connection: connection},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<Map<String, Object?>> executeModernMessage(
    _i10.MongoModernMessage? message, {
    _i2.Connection? connection,
    bool? skipStateCheck = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #executeModernMessage,
          [message],
          {
            #connection: connection,
            #skipStateCheck: skipStateCheck,
          },
        ),
        returnValue:
            _i9.Future<Map<String, Object?>>.value(<String, Object?>{}),
      ) as _i9.Future<Map<String, Object?>>);

  @override
  _i9.Future<dynamic> open({
    _i2.WriteConcern? writeConcern = _i2.WriteConcern.acknowledged,
    bool? secure = false,
    bool? tlsAllowInvalidCertificates = false,
    String? tlsCAFile,
    String? tlsCertificateKeyFile,
    String? tlsCertificateKeyFilePassword,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #open,
          [],
          {
            #writeConcern: writeConcern,
            #secure: secure,
            #tlsAllowInvalidCertificates: tlsAllowInvalidCertificates,
            #tlsCAFile: tlsCAFile,
            #tlsCertificateKeyFile: tlsCertificateKeyFile,
            #tlsCertificateKeyFilePassword: tlsCertificateKeyFilePassword,
          },
        ),
        returnValue: _i9.Future<dynamic>.value(),
      ) as _i9.Future<dynamic>);

  @override
  _i9.Future<Map<String, dynamic>> executeDbCommand(
    _i2.MongoMessage? message, {
    _i2.Connection? connection,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #executeDbCommand,
          [message],
          {#connection: connection},
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  bool documentIsNotAnError(dynamic firstRepliedDocument) =>
      (super.noSuchMethod(
        Invocation.method(
          #documentIsNotAnError,
          [firstRepliedDocument],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i9.Future<bool> dropCollection(String? collectionName) =>
      (super.noSuchMethod(
        Invocation.method(
          #dropCollection,
          [collectionName],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<dynamic> drop() => (super.noSuchMethod(
        Invocation.method(
          #drop,
          [],
        ),
        returnValue: _i9.Future<dynamic>.value(),
      ) as _i9.Future<dynamic>);

  @override
  _i9.Future<Map<String, dynamic>> removeFromCollection(
    String? collectionName, [
    Map<String, dynamic>? selector = const {},
    _i2.WriteConcern? writeConcern,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFromCollection,
          [
            collectionName,
            selector,
            writeConcern,
          ],
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<Map<String, dynamic>> getLastError(
          [_i2.WriteConcern? writeConcern]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLastError,
          [writeConcern],
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<Map<String, dynamic>> getNonce({_i2.Connection? connection}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNonce,
          [],
          {#connection: connection},
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<Map<String, dynamic>> getBuildInfo({_i2.Connection? connection}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBuildInfo,
          [],
          {#connection: connection},
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<Map<String, dynamic>> isMaster({_i2.Connection? connection}) =>
      (super.noSuchMethod(
        Invocation.method(
          #isMaster,
          [],
          {#connection: connection},
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<Map<String, dynamic>> wait() => (super.noSuchMethod(
        Invocation.method(
          #wait,
          [],
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<dynamic> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i9.Future<dynamic>.value(),
      ) as _i9.Future<dynamic>);

  @override
  _i9.Future<List<dynamic>> listDatabases() => (super.noSuchMethod(
        Invocation.method(
          #listDatabases,
          [],
        ),
        returnValue: _i9.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i9.Future<List<dynamic>>);

  @override
  _i9.Stream<Map<String, dynamic>> collectionsInfoCursor(
          [String? collectionName]) =>
      (super.noSuchMethod(
        Invocation.method(
          #collectionsInfoCursor,
          [collectionName],
        ),
        returnValue: _i9.Stream<Map<String, dynamic>>.empty(),
      ) as _i9.Stream<Map<String, dynamic>>);

  @override
  _i9.Future<List<String?>> listCollections() => (super.noSuchMethod(
        Invocation.method(
          #listCollections,
          [],
        ),
        returnValue: _i9.Future<List<String?>>.value(<String?>[]),
      ) as _i9.Future<List<String?>>);

  @override
  _i9.Future<List<Map<String, dynamic>>> getCollectionInfos(
          [Map<String, dynamic>? filter = const {}]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCollectionInfos,
          [filter],
        ),
        returnValue: _i9.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i9.Future<List<Map<String, dynamic>>>);

  @override
  _i9.Future<List<String?>> getCollectionNames(
          [Map<String, dynamic>? filter = const {}]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCollectionNames,
          [filter],
        ),
        returnValue: _i9.Future<List<String?>>.value(<String?>[]),
      ) as _i9.Future<List<String?>>);

  @override
  _i9.Future<bool> authenticate(
    String? userName,
    String? password, {
    _i2.Connection? connection,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #authenticate,
          [
            userName,
            password,
          ],
          {#connection: connection},
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<List<dynamic>> indexInformation([String? collectionName]) =>
      (super.noSuchMethod(
        Invocation.method(
          #indexInformation,
          [collectionName],
        ),
        returnValue: _i9.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i9.Future<List<dynamic>>);

  @override
  _i9.Future<Map<String, dynamic>> createIndex(
    String? collectionName, {
    String? key,
    Map<String, dynamic>? keys,
    bool? unique,
    bool? sparse,
    bool? background,
    bool? dropDups,
    Map<String, dynamic>? partialFilterExpression,
    String? name,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createIndex,
          [collectionName],
          {
            #key: key,
            #keys: keys,
            #unique: unique,
            #sparse: sparse,
            #background: background,
            #dropDups: dropDups,
            #partialFilterExpression: partialFilterExpression,
            #name: name,
          },
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<dynamic> ensureIndex(
    String? collectionName, {
    String? key,
    Map<String, dynamic>? keys,
    bool? unique,
    bool? sparse,
    bool? background,
    bool? dropDups,
    Map<String, dynamic>? partialFilterExpression,
    String? name,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #ensureIndex,
          [collectionName],
          {
            #key: key,
            #keys: keys,
            #unique: unique,
            #sparse: sparse,
            #background: background,
            #dropDups: dropDups,
            #partialFilterExpression: partialFilterExpression,
            #name: name,
          },
        ),
        returnValue: _i9.Future<dynamic>.value(),
      ) as _i9.Future<dynamic>);

  @override
  _i9.Future<Map<String, Object?>> modernDropDatabase({
    _i11.DropDatabaseOptions? dropOptions,
    Map<String, Object>? rawOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #modernDropDatabase,
          [],
          {
            #dropOptions: dropOptions,
            #rawOptions: rawOptions,
          },
        ),
        returnValue:
            _i9.Future<Map<String, Object?>>.value(<String, Object?>{}),
      ) as _i9.Future<Map<String, Object?>>);

  @override
  _i9.Future<Map<String, Object?>> serverStatus(
          {Map<String, Object>? options}) =>
      (super.noSuchMethod(
        Invocation.method(
          #serverStatus,
          [],
          {#options: options},
        ),
        returnValue:
            _i9.Future<Map<String, Object?>>.value(<String, Object?>{}),
      ) as _i9.Future<Map<String, Object?>>);

  @override
  _i9.Future<Map<String, Object?>> createCollection(
    String? name, {
    _i3.CreateCollectionOptions? createCollectionOptions,
    Map<String, Object>? rawOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCollection,
          [name],
          {
            #createCollectionOptions: createCollectionOptions,
            #rawOptions: rawOptions,
          },
        ),
        returnValue:
            _i9.Future<Map<String, Object?>>.value(<String, Object?>{}),
      ) as _i9.Future<Map<String, Object?>>);

  @override
  _i9.Stream<Map<String, dynamic>> modernListCollections({
    _i12.SelectorBuilder? selector,
    Map<String, Object?>? filter,
    _i13.ListCollectionsOptions? findOptions,
    Map<String, Object>? rawOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #modernListCollections,
          [],
          {
            #selector: selector,
            #filter: filter,
            #findOptions: findOptions,
            #rawOptions: rawOptions,
          },
        ),
        returnValue: _i9.Stream<Map<String, dynamic>>.empty(),
      ) as _i9.Stream<Map<String, dynamic>>);

  @override
  _i9.Future<Map<String, Object?>> createView(
    String? view,
    String? source,
    List<dynamic>? pipeline, {
    _i3.CreateViewOptions? createViewOptions,
    Map<String, Object>? rawOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createView,
          [
            view,
            source,
            pipeline,
          ],
          {
            #createViewOptions: createViewOptions,
            #rawOptions: rawOptions,
          },
        ),
        returnValue:
            _i9.Future<Map<String, Object?>>.value(<String, Object?>{}),
      ) as _i9.Future<Map<String, Object?>>);

  @override
  _i9.Future<Map<String, Object?>> modernDrop(
    String? collectionNAme, {
    _i14.DropOptions? dropOptions,
    Map<String, Object>? rawOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #modernDrop,
          [collectionNAme],
          {
            #dropOptions: dropOptions,
            #rawOptions: rawOptions,
          },
        ),
        returnValue:
            _i9.Future<Map<String, Object?>>.value(<String, Object?>{}),
      ) as _i9.Future<Map<String, Object?>>);

  @override
  _i9.Stream<Map<String, dynamic>> aggregate(
    List<Map<String, Object>>? pipeline, {
    bool? explain,
    Map<String, Object>? cursor,
    String? hint,
    Map<String, Object>? hintDocument,
    _i3.AggregateOptions? aggregateOptions,
    Map<String, Object>? rawOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #aggregate,
          [pipeline],
          {
            #explain: explain,
            #cursor: cursor,
            #hint: hint,
            #hintDocument: hintDocument,
            #aggregateOptions: aggregateOptions,
            #rawOptions: rawOptions,
          },
        ),
        returnValue: _i9.Stream<Map<String, dynamic>>.empty(),
      ) as _i9.Stream<Map<String, dynamic>>);

  @override
  _i9.Future<Map<String, Object?>> runCommand(Map<String, Object>? command) =>
      (super.noSuchMethod(
        Invocation.method(
          #runCommand,
          [command],
        ),
        returnValue:
            _i9.Future<Map<String, Object?>>.value(<String, Object?>{}),
      ) as _i9.Future<Map<String, Object?>>);

  @override
  _i9.Future<Map<String, Object?>> pingCommand() => (super.noSuchMethod(
        Invocation.method(
          #pingCommand,
          [],
        ),
        returnValue:
            _i9.Future<Map<String, Object?>>.value(<String, Object?>{}),
      ) as _i9.Future<Map<String, Object?>>);
}

/// A class which mocks [DbCollection].
///
/// See the documentation for Mockito's code generation for more information.
class MockDbCollection extends _i1.Mock implements _i2.DbCollection {
  MockDbCollection() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Db get db => (super.noSuchMethod(
        Invocation.getter(#db),
        returnValue: _FakeDb_5(
          this,
          Invocation.getter(#db),
        ),
      ) as _i2.Db);

  @override
  set db(_i2.Db? _db) => super.noSuchMethod(
        Invocation.setter(
          #db,
          _db,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get collectionName => (super.noSuchMethod(
        Invocation.getter(#collectionName),
        returnValue: _i15.dummyValue<String>(
          this,
          Invocation.getter(#collectionName),
        ),
      ) as String);

  @override
  set collectionName(String? _collectionName) => super.noSuchMethod(
        Invocation.setter(
          #collectionName,
          _collectionName,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.ReadPreference get readPreference => (super.noSuchMethod(
        Invocation.getter(#readPreference),
        returnValue: _FakeReadPreference_1(
          this,
          Invocation.getter(#readPreference),
        ),
      ) as _i3.ReadPreference);

  @override
  set readPreference(_i3.ReadPreference? _readPreference) => super.noSuchMethod(
        Invocation.setter(
          #readPreference,
          _readPreference,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String fullName() => (super.noSuchMethod(
        Invocation.method(
          #fullName,
          [],
        ),
        returnValue: _i15.dummyValue<String>(
          this,
          Invocation.method(
            #fullName,
            [],
          ),
        ),
      ) as String);

  @override
  _i9.Future<Map<String, dynamic>> save(
    Map<String, dynamic>? document, {
    _i2.WriteConcern? writeConcern,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #save,
          [document],
          {#writeConcern: writeConcern},
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<Map<String, dynamic>> insertAll(
    List<Map<String, dynamic>>? documents, {
    _i2.WriteConcern? writeConcern,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertAll,
          [documents],
          {#writeConcern: writeConcern},
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<Map<String, dynamic>> legacyInsertAll(
    List<Map<String, dynamic>>? documents, {
    _i2.WriteConcern? writeConcern,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #legacyInsertAll,
          [documents],
          {#writeConcern: writeConcern},
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<Map<String, dynamic>> update(
    dynamic selector,
    dynamic document, {
    bool? upsert = false,
    bool? multiUpdate = false,
    _i2.WriteConcern? writeConcern,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [
            selector,
            document,
          ],
          {
            #upsert: upsert,
            #multiUpdate: multiUpdate,
            #writeConcern: writeConcern,
          },
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<Map<String, dynamic>> legacyUpdate(
    dynamic selector,
    dynamic document, {
    bool? upsert = false,
    bool? multiUpdate = false,
    _i2.WriteConcern? writeConcern,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #legacyUpdate,
          [
            selector,
            document,
          ],
          {
            #upsert: upsert,
            #multiUpdate: multiUpdate,
            #writeConcern: writeConcern,
          },
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Stream<Map<String, dynamic>> find([dynamic selector]) =>
      (super.noSuchMethod(
        Invocation.method(
          #find,
          [selector],
        ),
        returnValue: _i9.Stream<Map<String, dynamic>>.empty(),
      ) as _i9.Stream<Map<String, dynamic>>);

  @override
  _i9.Stream<Map<String, dynamic>> legacyFind([dynamic selector]) =>
      (super.noSuchMethod(
        Invocation.method(
          #legacyFind,
          [selector],
        ),
        returnValue: _i9.Stream<Map<String, dynamic>>.empty(),
      ) as _i9.Stream<Map<String, dynamic>>);

  @override
  _i2.Cursor createCursor([dynamic selector]) => (super.noSuchMethod(
        Invocation.method(
          #createCursor,
          [selector],
        ),
        returnValue: _FakeCursor_6(
          this,
          Invocation.method(
            #createCursor,
            [selector],
          ),
        ),
      ) as _i2.Cursor);

  @override
  _i9.Future<Map<String, dynamic>?> findOne([dynamic selector]) =>
      (super.noSuchMethod(
        Invocation.method(
          #findOne,
          [selector],
        ),
        returnValue: _i9.Future<Map<String, dynamic>?>.value(),
      ) as _i9.Future<Map<String, dynamic>?>);

  @override
  _i9.Future<Map<String, dynamic>?> legacyFindOne([dynamic selector]) =>
      (super.noSuchMethod(
        Invocation.method(
          #legacyFindOne,
          [selector],
        ),
        returnValue: _i9.Future<Map<String, dynamic>?>.value(),
      ) as _i9.Future<Map<String, dynamic>?>);

  @override
  _i9.Future<Map<String, dynamic>?> findAndModify({
    dynamic query,
    dynamic sort,
    bool? remove,
    dynamic update,
    bool? returnNew,
    dynamic fields,
    bool? upsert,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #findAndModify,
          [],
          {
            #query: query,
            #sort: sort,
            #remove: remove,
            #update: update,
            #returnNew: returnNew,
            #fields: fields,
            #upsert: upsert,
          },
        ),
        returnValue: _i9.Future<Map<String, dynamic>?>.value(),
      ) as _i9.Future<Map<String, dynamic>?>);

  @override
  _i9.Future<Map<String, dynamic>?> legacyFindAndModify({
    dynamic query,
    dynamic sort,
    bool? remove,
    dynamic update,
    bool? returnNew,
    dynamic fields,
    bool? upsert,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #legacyFindAndModify,
          [],
          {
            #query: query,
            #sort: sort,
            #remove: remove,
            #update: update,
            #returnNew: returnNew,
            #fields: fields,
            #upsert: upsert,
          },
        ),
        returnValue: _i9.Future<Map<String, dynamic>?>.value(),
      ) as _i9.Future<Map<String, dynamic>?>);

  @override
  _i9.Future<bool> drop() => (super.noSuchMethod(
        Invocation.method(
          #drop,
          [],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<Map<String, dynamic>> remove(
    dynamic selector, {
    _i2.WriteConcern? writeConcern,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #remove,
          [selector],
          {#writeConcern: writeConcern},
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<Map<String, dynamic>> legacyRemove(
    dynamic selector, {
    _i2.WriteConcern? writeConcern,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #legacyRemove,
          [selector],
          {#writeConcern: writeConcern},
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<int> count([dynamic selector]) => (super.noSuchMethod(
        Invocation.method(
          #count,
          [selector],
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<int> legacyCount([dynamic selector]) => (super.noSuchMethod(
        Invocation.method(
          #legacyCount,
          [selector],
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<Map<String, dynamic>> distinct(
    String? field, [
    dynamic selector,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #distinct,
          [
            field,
            selector,
          ],
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<Map<String, dynamic>> legacyDistinct(
    String? field, [
    dynamic selector,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #legacyDistinct,
          [
            field,
            selector,
          ],
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<Map<String, dynamic>> aggregate(
    List<dynamic>? pipeline, {
    bool? allowDiskUse = false,
    Map<String, Object>? cursor,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #aggregate,
          [pipeline],
          {
            #allowDiskUse: allowDiskUse,
            #cursor: cursor,
          },
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Stream<Map<String, dynamic>> aggregateToStream(
    List<Map<String, Object>>? pipeline, {
    Map<String, Object>? cursorOptions = const {},
    bool? allowDiskUse = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #aggregateToStream,
          [pipeline],
          {
            #cursorOptions: cursorOptions,
            #allowDiskUse: allowDiskUse,
          },
        ),
        returnValue: _i9.Stream<Map<String, dynamic>>.empty(),
      ) as _i9.Stream<Map<String, dynamic>>);

  @override
  _i9.Stream<Map<String, dynamic>> legacyAggregateToStream(
    List<dynamic>? pipeline, {
    Map<String, dynamic>? cursorOptions = const {},
    bool? allowDiskUse = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #legacyAggregateToStream,
          [pipeline],
          {
            #cursorOptions: cursorOptions,
            #allowDiskUse: allowDiskUse,
          },
        ),
        returnValue: _i9.Stream<Map<String, dynamic>>.empty(),
      ) as _i9.Stream<Map<String, dynamic>>);

  @override
  _i9.Future<Map<String, dynamic>> insert(
    Map<String, dynamic>? document, {
    _i2.WriteConcern? writeConcern,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #insert,
          [document],
          {#writeConcern: writeConcern},
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<Map<String, dynamic>> legacyInsert(
    Map<String, dynamic>? document, {
    _i2.WriteConcern? writeConcern,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #legacyInsert,
          [document],
          {#writeConcern: writeConcern},
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<List<Map<String, dynamic>>> getIndexes() => (super.noSuchMethod(
        Invocation.method(
          #getIndexes,
          [],
        ),
        returnValue: _i9.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i9.Future<List<Map<String, dynamic>>>);

  @override
  _i9.Future<Map<String, dynamic>> createIndex({
    String? key,
    Map<String, dynamic>? keys,
    bool? unique,
    bool? sparse,
    bool? background,
    bool? dropDups,
    Map<String, dynamic>? partialFilterExpression,
    String? name,
    bool? modernReply,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createIndex,
          [],
          {
            #key: key,
            #keys: keys,
            #unique: unique,
            #sparse: sparse,
            #background: background,
            #dropDups: dropDups,
            #partialFilterExpression: partialFilterExpression,
            #name: name,
            #modernReply: modernReply,
          },
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Stream<Map<String, dynamic>> listIndexes({
    int? batchSize,
    String? comment,
    Map<String, Object>? rawOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listIndexes,
          [],
          {
            #batchSize: batchSize,
            #comment: comment,
            #rawOptions: rawOptions,
          },
        ),
        returnValue: _i9.Stream<Map<String, dynamic>>.empty(),
      ) as _i9.Stream<Map<String, dynamic>>);

  @override
  _i9.Future<Map<String, dynamic>> dropIndexes(
    Object? index, {
    _i2.WriteConcern? writeConcern,
    String? comment,
    Map<String, Object>? rawOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #dropIndexes,
          [index],
          {
            #writeConcern: writeConcern,
            #comment: comment,
            #rawOptions: rawOptions,
          },
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<_i3.WriteResult> insertOne(
    Map<String, dynamic>? document, {
    _i2.WriteConcern? writeConcern,
    bool? bypassDocumentValidation,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertOne,
          [document],
          {
            #writeConcern: writeConcern,
            #bypassDocumentValidation: bypassDocumentValidation,
          },
        ),
        returnValue: _i9.Future<_i3.WriteResult>.value(_FakeWriteResult_7(
          this,
          Invocation.method(
            #insertOne,
            [document],
            {
              #writeConcern: writeConcern,
              #bypassDocumentValidation: bypassDocumentValidation,
            },
          ),
        )),
      ) as _i9.Future<_i3.WriteResult>);

  @override
  _i9.Future<_i3.BulkWriteResult> insertMany(
    List<Map<String, dynamic>>? documents, {
    _i2.WriteConcern? writeConcern,
    bool? ordered,
    bool? bypassDocumentValidation,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertMany,
          [documents],
          {
            #writeConcern: writeConcern,
            #ordered: ordered,
            #bypassDocumentValidation: bypassDocumentValidation,
          },
        ),
        returnValue:
            _i9.Future<_i3.BulkWriteResult>.value(_FakeBulkWriteResult_8(
          this,
          Invocation.method(
            #insertMany,
            [documents],
            {
              #writeConcern: writeConcern,
              #ordered: ordered,
              #bypassDocumentValidation: bypassDocumentValidation,
            },
          ),
        )),
      ) as _i9.Future<_i3.BulkWriteResult>);

  @override
  _i9.Future<_i3.WriteResult> deleteOne(
    dynamic selector, {
    _i2.WriteConcern? writeConcern,
    _i3.CollationOptions? collation,
    String? hint,
    Map<String, Object>? hintDocument,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteOne,
          [selector],
          {
            #writeConcern: writeConcern,
            #collation: collation,
            #hint: hint,
            #hintDocument: hintDocument,
          },
        ),
        returnValue: _i9.Future<_i3.WriteResult>.value(_FakeWriteResult_7(
          this,
          Invocation.method(
            #deleteOne,
            [selector],
            {
              #writeConcern: writeConcern,
              #collation: collation,
              #hint: hint,
              #hintDocument: hintDocument,
            },
          ),
        )),
      ) as _i9.Future<_i3.WriteResult>);

  @override
  _i9.Future<_i3.WriteResult> deleteMany(
    dynamic selector, {
    _i2.WriteConcern? writeConcern,
    _i3.CollationOptions? collation,
    String? hint,
    Map<String, Object>? hintDocument,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteMany,
          [selector],
          {
            #writeConcern: writeConcern,
            #collation: collation,
            #hint: hint,
            #hintDocument: hintDocument,
          },
        ),
        returnValue: _i9.Future<_i3.WriteResult>.value(_FakeWriteResult_7(
          this,
          Invocation.method(
            #deleteMany,
            [selector],
            {
              #writeConcern: writeConcern,
              #collation: collation,
              #hint: hint,
              #hintDocument: hintDocument,
            },
          ),
        )),
      ) as _i9.Future<_i3.WriteResult>);

  @override
  _i9.Future<Map<String, dynamic>> modernUpdate(
    dynamic selector,
    dynamic update, {
    bool? upsert,
    bool? multi,
    _i2.WriteConcern? writeConcern,
    _i3.CollationOptions? collation,
    List<dynamic>? arrayFilters,
    String? hint,
    Map<String, Object>? hintDocument,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #modernUpdate,
          [
            selector,
            update,
          ],
          {
            #upsert: upsert,
            #multi: multi,
            #writeConcern: writeConcern,
            #collation: collation,
            #arrayFilters: arrayFilters,
            #hint: hint,
            #hintDocument: hintDocument,
          },
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<_i3.WriteResult> replaceOne(
    dynamic selector,
    Map<String, dynamic>? update, {
    bool? upsert,
    _i2.WriteConcern? writeConcern,
    _i3.CollationOptions? collation,
    String? hint,
    Map<String, Object>? hintDocument,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceOne,
          [
            selector,
            update,
          ],
          {
            #upsert: upsert,
            #writeConcern: writeConcern,
            #collation: collation,
            #hint: hint,
            #hintDocument: hintDocument,
          },
        ),
        returnValue: _i9.Future<_i3.WriteResult>.value(_FakeWriteResult_7(
          this,
          Invocation.method(
            #replaceOne,
            [
              selector,
              update,
            ],
            {
              #upsert: upsert,
              #writeConcern: writeConcern,
              #collation: collation,
              #hint: hint,
              #hintDocument: hintDocument,
            },
          ),
        )),
      ) as _i9.Future<_i3.WriteResult>);

  @override
  _i9.Future<_i3.WriteResult> updateOne(
    dynamic selector,
    dynamic update, {
    bool? upsert,
    _i2.WriteConcern? writeConcern,
    _i3.CollationOptions? collation,
    List<dynamic>? arrayFilters,
    String? hint,
    Map<String, Object>? hintDocument,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateOne,
          [
            selector,
            update,
          ],
          {
            #upsert: upsert,
            #writeConcern: writeConcern,
            #collation: collation,
            #arrayFilters: arrayFilters,
            #hint: hint,
            #hintDocument: hintDocument,
          },
        ),
        returnValue: _i9.Future<_i3.WriteResult>.value(_FakeWriteResult_7(
          this,
          Invocation.method(
            #updateOne,
            [
              selector,
              update,
            ],
            {
              #upsert: upsert,
              #writeConcern: writeConcern,
              #collation: collation,
              #arrayFilters: arrayFilters,
              #hint: hint,
              #hintDocument: hintDocument,
            },
          ),
        )),
      ) as _i9.Future<_i3.WriteResult>);

  @override
  _i9.Future<_i3.WriteResult> updateMany(
    dynamic selector,
    dynamic update, {
    bool? upsert,
    _i2.WriteConcern? writeConcern,
    _i3.CollationOptions? collation,
    List<dynamic>? arrayFilters,
    String? hint,
    Map<String, Object>? hintDocument,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMany,
          [
            selector,
            update,
          ],
          {
            #upsert: upsert,
            #writeConcern: writeConcern,
            #collation: collation,
            #arrayFilters: arrayFilters,
            #hint: hint,
            #hintDocument: hintDocument,
          },
        ),
        returnValue: _i9.Future<_i3.WriteResult>.value(_FakeWriteResult_7(
          this,
          Invocation.method(
            #updateMany,
            [
              selector,
              update,
            ],
            {
              #upsert: upsert,
              #writeConcern: writeConcern,
              #collation: collation,
              #arrayFilters: arrayFilters,
              #hint: hint,
              #hintDocument: hintDocument,
            },
          ),
        )),
      ) as _i9.Future<_i3.WriteResult>);

  @override
  _i9.Future<_i3.FindAndModifyResult> modernFindAndModify({
    dynamic query,
    dynamic sort,
    bool? remove,
    dynamic update,
    bool? returnNew,
    dynamic fields,
    bool? upsert,
    List<dynamic>? arrayFilters,
    String? hint,
    Map<String, Object>? hintDocument,
    _i3.FindAndModifyOptions? findAndModifyOptions,
    Map<String, Object>? rawOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #modernFindAndModify,
          [],
          {
            #query: query,
            #sort: sort,
            #remove: remove,
            #update: update,
            #returnNew: returnNew,
            #fields: fields,
            #upsert: upsert,
            #arrayFilters: arrayFilters,
            #hint: hint,
            #hintDocument: hintDocument,
            #findAndModifyOptions: findAndModifyOptions,
            #rawOptions: rawOptions,
          },
        ),
        returnValue: _i9.Future<_i3.FindAndModifyResult>.value(
            _FakeFindAndModifyResult_9(
          this,
          Invocation.method(
            #modernFindAndModify,
            [],
            {
              #query: query,
              #sort: sort,
              #remove: remove,
              #update: update,
              #returnNew: returnNew,
              #fields: fields,
              #upsert: upsert,
              #arrayFilters: arrayFilters,
              #hint: hint,
              #hintDocument: hintDocument,
              #findAndModifyOptions: findAndModifyOptions,
              #rawOptions: rawOptions,
            },
          ),
        )),
      ) as _i9.Future<_i3.FindAndModifyResult>);

  @override
  _i9.Stream<Map<String, dynamic>> modernFind({
    _i12.SelectorBuilder? selector,
    Map<String, Object?>? filter,
    Map<String, Object>? sort,
    Map<String, Object>? projection,
    String? hint,
    Map<String, Object>? hintDocument,
    int? skip,
    int? limit,
    _i3.FindOptions? findOptions,
    Map<String, Object>? rawOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #modernFind,
          [],
          {
            #selector: selector,
            #filter: filter,
            #sort: sort,
            #projection: projection,
            #hint: hint,
            #hintDocument: hintDocument,
            #skip: skip,
            #limit: limit,
            #findOptions: findOptions,
            #rawOptions: rawOptions,
          },
        ),
        returnValue: _i9.Stream<Map<String, dynamic>>.empty(),
      ) as _i9.Stream<Map<String, dynamic>>);

  @override
  _i9.Future<Map<String, dynamic>?> modernFindOne({
    _i12.SelectorBuilder? selector,
    Map<String, Object?>? filter,
    Map<String, Object>? sort,
    Map<String, Object>? projection,
    String? hint,
    Map<String, Object>? hintDocument,
    int? skip,
    _i3.FindOptions? findOptions,
    Map<String, Object>? rawOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #modernFindOne,
          [],
          {
            #selector: selector,
            #filter: filter,
            #sort: sort,
            #projection: projection,
            #hint: hint,
            #hintDocument: hintDocument,
            #skip: skip,
            #findOptions: findOptions,
            #rawOptions: rawOptions,
          },
        ),
        returnValue: _i9.Future<Map<String, dynamic>?>.value(),
      ) as _i9.Future<Map<String, dynamic>?>);

  @override
  _i9.Future<_i4.DistinctResult> modernDistinct(
    String? field, {
    dynamic query,
    _i16.DistinctOptions? distinctOptions,
    Map<String, Object>? rawOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #modernDistinct,
          [field],
          {
            #query: query,
            #distinctOptions: distinctOptions,
            #rawOptions: rawOptions,
          },
        ),
        returnValue:
            _i9.Future<_i4.DistinctResult>.value(_FakeDistinctResult_10(
          this,
          Invocation.method(
            #modernDistinct,
            [field],
            {
              #query: query,
              #distinctOptions: distinctOptions,
              #rawOptions: rawOptions,
            },
          ),
        )),
      ) as _i9.Future<_i4.DistinctResult>);

  @override
  _i9.Future<Map<String, Object?>> modernDistinctMap(
    String? field, {
    dynamic query,
    _i16.DistinctOptions? distinctOptions,
    Map<String, Object>? rawOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #modernDistinctMap,
          [field],
          {
            #query: query,
            #distinctOptions: distinctOptions,
            #rawOptions: rawOptions,
          },
        ),
        returnValue:
            _i9.Future<Map<String, Object?>>.value(<String, Object?>{}),
      ) as _i9.Future<Map<String, Object?>>);

  @override
  _i9.Stream<Map<String, dynamic>> modernAggregate(
    dynamic pipeline, {
    bool? explain,
    Map<String, Object>? cursor,
    String? hint,
    Map<String, Object>? hintDocument,
    _i3.AggregateOptions? aggregateOptions,
    Map<String, Object>? rawOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #modernAggregate,
          [pipeline],
          {
            #explain: explain,
            #cursor: cursor,
            #hint: hint,
            #hintDocument: hintDocument,
            #aggregateOptions: aggregateOptions,
            #rawOptions: rawOptions,
          },
        ),
        returnValue: _i9.Stream<Map<String, dynamic>>.empty(),
      ) as _i9.Stream<Map<String, dynamic>>);

  @override
  _i5.ModernCursor modernAggregateCursor(
    dynamic pipeline, {
    bool? explain,
    Map<String, Object>? cursor,
    String? hint,
    Map<String, Object>? hintDocument,
    _i3.AggregateOptions? aggregateOptions,
    Map<String, Object>? rawOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #modernAggregateCursor,
          [pipeline],
          {
            #explain: explain,
            #cursor: cursor,
            #hint: hint,
            #hintDocument: hintDocument,
            #aggregateOptions: aggregateOptions,
            #rawOptions: rawOptions,
          },
        ),
        returnValue: _FakeModernCursor_11(
          this,
          Invocation.method(
            #modernAggregateCursor,
            [pipeline],
            {
              #explain: explain,
              #cursor: cursor,
              #hint: hint,
              #hintDocument: hintDocument,
              #aggregateOptions: aggregateOptions,
              #rawOptions: rawOptions,
            },
          ),
        ),
      ) as _i5.ModernCursor);

  @override
  _i9.Stream<dynamic> watch(
    Object? pipeline, {
    int? batchSize,
    String? hint,
    Map<String, Object>? hintDocument,
    _i3.ChangeStreamOptions? changeStreamOptions,
    Map<String, Object>? rawOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #watch,
          [pipeline],
          {
            #batchSize: batchSize,
            #hint: hint,
            #hintDocument: hintDocument,
            #changeStreamOptions: changeStreamOptions,
            #rawOptions: rawOptions,
          },
        ),
        returnValue: _i9.Stream<dynamic>.empty(),
      ) as _i9.Stream<dynamic>);

  @override
  _i5.ModernCursor watchCursor(
    Object? pipeline, {
    int? batchSize,
    String? hint,
    Map<String, Object>? hintDocument,
    _i3.ChangeStreamOptions? changeStreamOptions,
    Map<String, Object>? rawOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchCursor,
          [pipeline],
          {
            #batchSize: batchSize,
            #hint: hint,
            #hintDocument: hintDocument,
            #changeStreamOptions: changeStreamOptions,
            #rawOptions: rawOptions,
          },
        ),
        returnValue: _FakeModernCursor_11(
          this,
          Invocation.method(
            #watchCursor,
            [pipeline],
            {
              #batchSize: batchSize,
              #hint: hint,
              #hintDocument: hintDocument,
              #changeStreamOptions: changeStreamOptions,
              #rawOptions: rawOptions,
            },
          ),
        ),
      ) as _i5.ModernCursor);

  @override
  _i9.Future<_i3.BulkWriteResult> bulkWrite(
    List<Map<String, Object>>? documents, {
    bool? ordered = true,
    _i2.WriteConcern? writeConcern,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #bulkWrite,
          [documents],
          {
            #ordered: ordered,
            #writeConcern: writeConcern,
          },
        ),
        returnValue:
            _i9.Future<_i3.BulkWriteResult>.value(_FakeBulkWriteResult_8(
          this,
          Invocation.method(
            #bulkWrite,
            [documents],
            {
              #ordered: ordered,
              #writeConcern: writeConcern,
            },
          ),
        )),
      ) as _i9.Future<_i3.BulkWriteResult>);

  @override
  _i9.Future<_i6.CountResult> modernCount({
    _i12.SelectorBuilder? selector,
    Map<String, Object?>? filter,
    int? limit,
    int? skip,
    _i3.CollationOptions? collation,
    String? hint,
    Map<String, Object>? hintDocument,
    _i17.CountOptions? countOptions,
    Map<String, Object>? rawOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #modernCount,
          [],
          {
            #selector: selector,
            #filter: filter,
            #limit: limit,
            #skip: skip,
            #collation: collation,
            #hint: hint,
            #hintDocument: hintDocument,
            #countOptions: countOptions,
            #rawOptions: rawOptions,
          },
        ),
        returnValue: _i9.Future<_i6.CountResult>.value(_FakeCountResult_12(
          this,
          Invocation.method(
            #modernCount,
            [],
            {
              #selector: selector,
              #filter: filter,
              #limit: limit,
              #skip: skip,
              #collation: collation,
              #hint: hint,
              #hintDocument: hintDocument,
              #countOptions: countOptions,
              #rawOptions: rawOptions,
            },
          ),
        )),
      ) as _i9.Future<_i6.CountResult>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockClient extends _i1.Mock implements _i7.Client {
  MockClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.ConnectionSettings get settings => (super.noSuchMethod(
        Invocation.getter(#settings),
        returnValue: _FakeConnectionSettings_13(
          this,
          Invocation.getter(#settings),
        ),
      ) as _i7.ConnectionSettings);

  @override
  _i8.TuningSettings get tuningSettings => (super.noSuchMethod(
        Invocation.getter(#tuningSettings),
        returnValue: _FakeTuningSettings_14(
          this,
          Invocation.getter(#tuningSettings),
        ),
      ) as _i8.TuningSettings);

  @override
  bool get handshaking => (super.noSuchMethod(
        Invocation.getter(#handshaking),
        returnValue: false,
      ) as bool);

  @override
  _i9.Future<dynamic> connect() => (super.noSuchMethod(
        Invocation.method(
          #connect,
          [],
        ),
        returnValue: _i9.Future<dynamic>.value(),
      ) as _i9.Future<dynamic>);

  @override
  _i9.Future<dynamic> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i9.Future<dynamic>.value(),
      ) as _i9.Future<dynamic>);

  @override
  _i9.Future<_i7.Channel> channel() => (super.noSuchMethod(
        Invocation.method(
          #channel,
          [],
        ),
        returnValue: _i9.Future<_i7.Channel>.value(_FakeChannel_15(
          this,
          Invocation.method(
            #channel,
            [],
          ),
        )),
      ) as _i9.Future<_i7.Channel>);

  @override
  _i9.StreamSubscription<Exception> errorListener(
    void Function(Exception)? onData, {
    Function? onError,
    void Function()? onDone,
    bool? cancelOnError,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #errorListener,
          [onData],
          {
            #onError: onError,
            #onDone: onDone,
            #cancelOnError: cancelOnError,
          },
        ),
        returnValue: _FakeStreamSubscription_16<Exception>(
          this,
          Invocation.method(
            #errorListener,
            [onData],
            {
              #onError: onError,
              #onDone: onDone,
              #cancelOnError: cancelOnError,
            },
          ),
        ),
      ) as _i9.StreamSubscription<Exception>);
}

/// A class which mocks [Channel].
///
/// See the documentation for Mockito's code generation for more information.
class MockChannel extends _i1.Mock implements _i7.Channel {
  MockChannel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i7.Channel> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i9.Future<_i7.Channel>.value(_FakeChannel_15(
          this,
          Invocation.method(
            #close,
            [],
          ),
        )),
      ) as _i9.Future<_i7.Channel>);

  @override
  _i9.Future<_i7.Queue> queue(
    String? name, {
    bool? passive = false,
    bool? durable = false,
    bool? exclusive = false,
    bool? autoDelete = false,
    bool? noWait = false,
    bool? declare = true,
    Map<String, Object>? arguments,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #queue,
          [name],
          {
            #passive: passive,
            #durable: durable,
            #exclusive: exclusive,
            #autoDelete: autoDelete,
            #noWait: noWait,
            #declare: declare,
            #arguments: arguments,
          },
        ),
        returnValue: _i9.Future<_i7.Queue>.value(_FakeQueue_17(
          this,
          Invocation.method(
            #queue,
            [name],
            {
              #passive: passive,
              #durable: durable,
              #exclusive: exclusive,
              #autoDelete: autoDelete,
              #noWait: noWait,
              #declare: declare,
              #arguments: arguments,
            },
          ),
        )),
      ) as _i9.Future<_i7.Queue>);

  @override
  _i9.Future<_i7.Queue> privateQueue({
    bool? noWait = false,
    Map<String, Object>? arguments,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #privateQueue,
          [],
          {
            #noWait: noWait,
            #arguments: arguments,
          },
        ),
        returnValue: _i9.Future<_i7.Queue>.value(_FakeQueue_17(
          this,
          Invocation.method(
            #privateQueue,
            [],
            {
              #noWait: noWait,
              #arguments: arguments,
            },
          ),
        )),
      ) as _i9.Future<_i7.Queue>);

  @override
  _i9.Future<_i7.Exchange> exchange(
    String? name,
    _i18.ExchangeType? type, {
    bool? passive = false,
    bool? durable = false,
    bool? noWait = false,
    Map<String, Object>? arguments,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #exchange,
          [
            name,
            type,
          ],
          {
            #passive: passive,
            #durable: durable,
            #noWait: noWait,
            #arguments: arguments,
          },
        ),
        returnValue: _i9.Future<_i7.Exchange>.value(_FakeExchange_18(
          this,
          Invocation.method(
            #exchange,
            [
              name,
              type,
            ],
            {
              #passive: passive,
              #durable: durable,
              #noWait: noWait,
              #arguments: arguments,
            },
          ),
        )),
      ) as _i9.Future<_i7.Exchange>);

  @override
  _i9.Future<_i7.Channel> qos(
    int? prefetchSize,
    int? prefetchCount, {
    bool? global = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #qos,
          [
            prefetchSize,
            prefetchCount,
          ],
          {#global: global},
        ),
        returnValue: _i9.Future<_i7.Channel>.value(_FakeChannel_15(
          this,
          Invocation.method(
            #qos,
            [
              prefetchSize,
              prefetchCount,
            ],
            {#global: global},
          ),
        )),
      ) as _i9.Future<_i7.Channel>);

  @override
  void ack(
    int? deliveryTag, {
    bool? multiple = false,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #ack,
          [deliveryTag],
          {#multiple: multiple},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<_i7.Channel> select() => (super.noSuchMethod(
        Invocation.method(
          #select,
          [],
        ),
        returnValue: _i9.Future<_i7.Channel>.value(_FakeChannel_15(
          this,
          Invocation.method(
            #select,
            [],
          ),
        )),
      ) as _i9.Future<_i7.Channel>);

  @override
  _i9.Future<_i7.Channel> commit() => (super.noSuchMethod(
        Invocation.method(
          #commit,
          [],
        ),
        returnValue: _i9.Future<_i7.Channel>.value(_FakeChannel_15(
          this,
          Invocation.method(
            #commit,
            [],
          ),
        )),
      ) as _i9.Future<_i7.Channel>);

  @override
  _i9.Future<_i7.Channel> rollback() => (super.noSuchMethod(
        Invocation.method(
          #rollback,
          [],
        ),
        returnValue: _i9.Future<_i7.Channel>.value(_FakeChannel_15(
          this,
          Invocation.method(
            #rollback,
            [],
          ),
        )),
      ) as _i9.Future<_i7.Channel>);

  @override
  _i9.Future<_i7.Channel> flow(bool? active) => (super.noSuchMethod(
        Invocation.method(
          #flow,
          [active],
        ),
        returnValue: _i9.Future<_i7.Channel>.value(_FakeChannel_15(
          this,
          Invocation.method(
            #flow,
            [active],
          ),
        )),
      ) as _i9.Future<_i7.Channel>);

  @override
  _i9.Future<_i7.Channel> recover(bool? requeue) => (super.noSuchMethod(
        Invocation.method(
          #recover,
          [requeue],
        ),
        returnValue: _i9.Future<_i7.Channel>.value(_FakeChannel_15(
          this,
          Invocation.method(
            #recover,
            [requeue],
          ),
        )),
      ) as _i9.Future<_i7.Channel>);

  @override
  _i9.StreamSubscription<_i7.BasicReturnMessage> basicReturnListener(
    void Function(_i7.BasicReturnMessage)? onData, {
    Function? onError,
    void Function()? onDone,
    bool? cancelOnError,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #basicReturnListener,
          [onData],
          {
            #onError: onError,
            #onDone: onDone,
            #cancelOnError: cancelOnError,
          },
        ),
        returnValue: _FakeStreamSubscription_16<_i7.BasicReturnMessage>(
          this,
          Invocation.method(
            #basicReturnListener,
            [onData],
            {
              #onError: onError,
              #onDone: onDone,
              #cancelOnError: cancelOnError,
            },
          ),
        ),
      ) as _i9.StreamSubscription<_i7.BasicReturnMessage>);

  @override
  _i9.StreamSubscription<_i7.PublishNotification> publishNotifier(
    void Function(_i7.PublishNotification)? onData, {
    Function? onError,
    void Function()? onDone,
    bool? cancelOnError,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #publishNotifier,
          [onData],
          {
            #onError: onError,
            #onDone: onDone,
            #cancelOnError: cancelOnError,
          },
        ),
        returnValue: _FakeStreamSubscription_16<_i7.PublishNotification>(
          this,
          Invocation.method(
            #publishNotifier,
            [onData],
            {
              #onError: onError,
              #onDone: onDone,
              #cancelOnError: cancelOnError,
            },
          ),
        ),
      ) as _i9.StreamSubscription<_i7.PublishNotification>);

  @override
  _i9.Future<dynamic> confirmPublishedMessages() => (super.noSuchMethod(
        Invocation.method(
          #confirmPublishedMessages,
          [],
        ),
        returnValue: _i9.Future<dynamic>.value(),
      ) as _i9.Future<dynamic>);
}

/// A class which mocks [Consumer].
///
/// See the documentation for Mockito's code generation for more information.
class MockConsumer extends _i1.Mock implements _i7.Consumer {
  MockConsumer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get tag => (super.noSuchMethod(
        Invocation.getter(#tag),
        returnValue: _i15.dummyValue<String>(
          this,
          Invocation.getter(#tag),
        ),
      ) as String);

  @override
  _i7.Channel get channel => (super.noSuchMethod(
        Invocation.getter(#channel),
        returnValue: _FakeChannel_15(
          this,
          Invocation.getter(#channel),
        ),
      ) as _i7.Channel);

  @override
  _i7.Queue get queue => (super.noSuchMethod(
        Invocation.getter(#queue),
        returnValue: _FakeQueue_17(
          this,
          Invocation.getter(#queue),
        ),
      ) as _i7.Queue);

  @override
  _i9.StreamSubscription<_i7.AmqpMessage> listen(
    void Function(_i7.AmqpMessage)? onData, {
    Function? onError,
    void Function()? onDone,
    bool? cancelOnError,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listen,
          [onData],
          {
            #onError: onError,
            #onDone: onDone,
            #cancelOnError: cancelOnError,
          },
        ),
        returnValue: _FakeStreamSubscription_16<_i7.AmqpMessage>(
          this,
          Invocation.method(
            #listen,
            [onData],
            {
              #onError: onError,
              #onDone: onDone,
              #cancelOnError: cancelOnError,
            },
          ),
        ),
      ) as _i9.StreamSubscription<_i7.AmqpMessage>);

  @override
  _i9.Future<_i7.Consumer> cancel({bool? noWait = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancel,
          [],
          {#noWait: noWait},
        ),
        returnValue: _i9.Future<_i7.Consumer>.value(_FakeConsumer_19(
          this,
          Invocation.method(
            #cancel,
            [],
            {#noWait: noWait},
          ),
        )),
      ) as _i9.Future<_i7.Consumer>);
}

/// A class which mocks [WriteResult].
///
/// See the documentation for Mockito's code generation for more information.
class MockWriteResult extends _i1.Mock implements _i3.WriteResult {
  MockWriteResult() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set id(dynamic _id) => super.noSuchMethod(
        Invocation.setter(
          #id,
          _id,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set document(Map<String, Object?>? _document) => super.noSuchMethod(
        Invocation.setter(
          #document,
          _document,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set writeError(_i19.WriteError? _writeError) => super.noSuchMethod(
        Invocation.setter(
          #writeError,
          _writeError,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasWriteErrors => (super.noSuchMethod(
        Invocation.getter(#hasWriteErrors),
        returnValue: false,
      ) as bool);

  @override
  int get writeErrorsNumber => (super.noSuchMethod(
        Invocation.getter(#writeErrorsNumber),
        returnValue: 0,
      ) as int);

  @override
  List<Map<String, Object?>> get serverResponses => (super.noSuchMethod(
        Invocation.getter(#serverResponses),
        returnValue: <Map<String, Object?>>[],
      ) as List<Map<String, Object?>>);

  @override
  set serverResponses(List<Map<String, Object?>>? _serverResponses) =>
      super.noSuchMethod(
        Invocation.setter(
          #serverResponses,
          _serverResponses,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set writeCommandType(_i20.WriteCommandType? _writeCommandType) =>
      super.noSuchMethod(
        Invocation.setter(
          #writeCommandType,
          _writeCommandType,
        ),
        returnValueForMissingStub: null,
      );

  @override
  int get nInserted => (super.noSuchMethod(
        Invocation.getter(#nInserted),
        returnValue: 0,
      ) as int);

  @override
  set nInserted(int? _nInserted) => super.noSuchMethod(
        Invocation.setter(
          #nInserted,
          _nInserted,
        ),
        returnValueForMissingStub: null,
      );

  @override
  int get nMatched => (super.noSuchMethod(
        Invocation.getter(#nMatched),
        returnValue: 0,
      ) as int);

  @override
  set nMatched(int? _nMatched) => super.noSuchMethod(
        Invocation.setter(
          #nMatched,
          _nMatched,
        ),
        returnValueForMissingStub: null,
      );

  @override
  int get nModified => (super.noSuchMethod(
        Invocation.getter(#nModified),
        returnValue: 0,
      ) as int);

  @override
  set nModified(int? _nModified) => super.noSuchMethod(
        Invocation.setter(
          #nModified,
          _nModified,
        ),
        returnValueForMissingStub: null,
      );

  @override
  int get nUpserted => (super.noSuchMethod(
        Invocation.getter(#nUpserted),
        returnValue: 0,
      ) as int);

  @override
  set nUpserted(int? _nUpserted) => super.noSuchMethod(
        Invocation.setter(
          #nUpserted,
          _nUpserted,
        ),
        returnValueForMissingStub: null,
      );

  @override
  int get nRemoved => (super.noSuchMethod(
        Invocation.getter(#nRemoved),
        returnValue: 0,
      ) as int);

  @override
  set nRemoved(int? _nRemoved) => super.noSuchMethod(
        Invocation.setter(
          #nRemoved,
          _nRemoved,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set writeConcernError(_i21.WriteConcernError? _writeConcernError) =>
      super.noSuchMethod(
        Invocation.setter(
          #writeConcernError,
          _writeConcernError,
        ),
        returnValueForMissingStub: null,
      );

  @override
  int get totalInserted => (super.noSuchMethod(
        Invocation.getter(#totalInserted),
        returnValue: 0,
      ) as int);

  @override
  bool get operationSucceeded => (super.noSuchMethod(
        Invocation.getter(#operationSucceeded),
        returnValue: false,
      ) as bool);

  @override
  bool get isAcknowledged => (super.noSuchMethod(
        Invocation.getter(#isAcknowledged),
        returnValue: false,
      ) as bool);

  @override
  bool get hasWriteConcernError => (super.noSuchMethod(
        Invocation.getter(#hasWriteConcernError),
        returnValue: false,
      ) as bool);

  @override
  bool get isSuccess => (super.noSuchMethod(
        Invocation.getter(#isSuccess),
        returnValue: false,
      ) as bool);

  @override
  bool get isSuspendedSuccess => (super.noSuchMethod(
        Invocation.getter(#isSuspendedSuccess),
        returnValue: false,
      ) as bool);

  @override
  bool get taskCompleted => (super.noSuchMethod(
        Invocation.getter(#taskCompleted),
        returnValue: false,
      ) as bool);

  @override
  bool get isPartialSuccess => (super.noSuchMethod(
        Invocation.getter(#isPartialSuccess),
        returnValue: false,
      ) as bool);

  @override
  bool get isSuspendedPartial => (super.noSuchMethod(
        Invocation.getter(#isSuspendedPartial),
        returnValue: false,
      ) as bool);

  @override
  bool get isPartial => (super.noSuchMethod(
        Invocation.getter(#isPartial),
        returnValue: false,
      ) as bool);

  @override
  bool get isFailure => (super.noSuchMethod(
        Invocation.getter(#isFailure),
        returnValue: false,
      ) as bool);

  @override
  double get ok => (super.noSuchMethod(
        Invocation.getter(#ok),
        returnValue: 0.0,
      ) as double);

  @override
  set ok(double? _ok) => super.noSuchMethod(
        Invocation.setter(
          #ok,
          _ok,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set errmsg(String? _errmsg) => super.noSuchMethod(
        Invocation.setter(
          #errmsg,
          _errmsg,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set code(int? _code) => super.noSuchMethod(
        Invocation.setter(
          #code,
          _code,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set codeName(String? _codeName) => super.noSuchMethod(
        Invocation.setter(
          #codeName,
          _codeName,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get success => (super.noSuchMethod(
        Invocation.getter(#success),
        returnValue: false,
      ) as bool);

  @override
  bool get failure => (super.noSuchMethod(
        Invocation.getter(#failure),
        returnValue: false,
      ) as bool);

  @override
  bool checkQueryExpectation(int? expectedMatches) => (super.noSuchMethod(
        Invocation.method(
          #checkQueryExpectation,
          [expectedMatches],
        ),
        returnValue: false,
      ) as bool);

  @override
  void extractBasic(Map<String, Object?>? document) => super.noSuchMethod(
        Invocation.method(
          #extractBasic,
          [document],
        ),
        returnValueForMissingStub: null,
      );
}
