name: mystiq_fortune_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
    
  mongo_dart: ^0.9.3
  flutter_svg: ^2.0.9
  google_sign_in: ^6.1.6
  http: ^0.13.6
  dart_amqp: ^0.2.5
  mailer: ^6.0.1
  flutter_dotenv: ^5.1.0
  image_picker: ^1.0.4
  googleapis_auth: ^1.4.1
  googleapis: ^11.4.0
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/google_logo.svg
    - assets/coffee_fortune.png
    - assets/zodiac/
    - .env
